server:
  port: 5000

spring:
  config:
    activate:
      on-profile: local
  r2dbc:
    url: r2dbc:mysql://
    username:
    password:
    pool:
      validation-query: SELECT 1
      initial-size: 2
      max-idle-time: 25s
      max-life-time: 30s
