server:
  port: 5000

spring:
  config:
    activate:
      on-profile: local
  r2dbc:
    url: r2dbc:mysql://localhost:3306/spring_boot_kotlin?serverZoneId=Asia/Seoul&sslMode=DISABLED
    username: admin
    password: modoric9876!
    pool:
      validation-query: SELECT 1
      initial-size: 2
      max-idle-time: 25s
      max-life-time: 30s
